name: Build ASI

on: [push]

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Prepare JS parts
      run: |
        mkdir -p ASI_Loader
        split -b 50K custom.js ASI_Loader/custom_part_
        for f in ASI_Loader/custom_part_*; do
          echo -n 'R"JSBIGDATA(' > "${f}.h"
          cat "$f" >> "${f}.h"
          echo ')JSBIGDATA"' >> "${f}.h"
        done
        
    - uses: actions/upload-artifact@v4
      with:
        name: prepared-sources
        path: ASI_Loader/

  build:
    needs: prepare
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/download-artifact@v4
      with:
        name: prepared-sources
        path: ASI_Loader/
    
    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1
    
    - name: Compile
      shell: cmd
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        cl /EHsc /LD ASI_Loader\ASI_Loader.cpp /Fe:ASI_Loader.asi /link shlwapi.lib
        if %errorlevel% neq 0 exit /b %errorlevel%
        
    - uses: actions/upload-artifact@v4
      with:
        name: ASI_Loader
        path: ASI_Loader.asi
