name: Build ASI Loader

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install CMake
      uses: lukka/get-cmake@latest
      
    - name: Configure CMake
      run: cmake -B build
      
    - name: Build
      run: cmake --build build --config Release
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ASI_Loader
        path: build/Release/ASI_Loader.asi
