name: Build ASI

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Prepare JS parts
      shell: bash
      run: |
        # 1. Разбиваем файл на части по 16KB
        mkdir -p ASI_Loader/js_parts
        split -b 16K custom.js ASI_Loader/js_parts/part_

        # 2. Генерируем файл с данными
        echo "const char* js_parts[] = {" > ASI_Loader/js_data.h
        for f in ASI_Loader/js_parts/part_*; do
          echo "R\"=====(" >> "$f.tmp"
          cat "$f" >> "$f.tmp"
          echo ")=====\"," >> "$f.tmp"
          cat "$f.tmp" >> ASI_Loader/js_data.h
        done
        echo "};" >> ASI_Loader/js_data.h
        echo "const int js_parts_count = $(ls ASI_Loader/js_parts/part_* | wc -l);" >> ASI_Loader/js_data.h

    - name: Setup MSVC
      uses: microsoft/setup-msbuild@v1

    - name: Compile
      shell: cmd
      run: |
        cl /EHsc /LD ASI_Loader/ASI_Loader.cpp /Fe:ASI_Loader.asi /link shlwapi.lib
        if %errorlevel% neq 0 exit /b %errorlevel%

    - uses: actions/upload-artifact@v4
      with:
        name: ASI_Loader
        path: ASI_Loader.asi
