name: Build ASI

on: [push]

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Split JS file
      run: |
        # 1. Разбиваем custom.js на части по 50KB
        mkdir -p ASI_Loader
        split -b 50K custom.js ASI_Loader/custom_js_part
        # 2. Конвертируем в .h-файлы
        for file in ASI_Loader/custom_js_part*; do
          echo "R\"=====(" > "${file}.h"
          cat "$file" >> "${file}.h"
          echo ")=====\"" >> "${file}.h"
        done
        
    - uses: actions/upload-artifact@v4
      with:
        name: prepared-sources
        path: ASI_Loader/

  build:
    needs: prepare
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/download-artifact@v4
      with:
        name: prepared-sources
        path: ASI_Loader/
    
    - name: Compile
      shell: cmd
      run: |
        cl /LD ASI_Loader\ASI_Loader.cpp /Fe:ASI_Loader.asi /link shlwapi.lib
        if %errorlevel% neq 0 exit /b %errorlevel%
        
    - uses: actions/upload-artifact@v4
      with:
        name: ASI_Loader
        path: ASI_Loader.asi
